version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: upstra-infra-control
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - upstra-infra-control_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis
    container_name: upstra-redis
    ports:
      - '6379:6379'

  prometheus:
    image: prom/prometheus:latest
    container_name: upstra-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped

volumes:
  upstra-infra-control_data:
  prometheus_data: