version: '3.8'

services:
  nest-app:
    container_name: nest-app
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: pg
    environment:
      POSTGRES_DB: pg
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_data:
