version: '3.8'

services:
  nest-app:
    container_name: nest-app
    build: .
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - postgres
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: upstra-infra-control
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - upstra-infra-control_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis
    container_name: upstra-redis
    ports:
      - '6379:6379'

volumes:
  upstra-infra-control_data:
