global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Backend NestJS metrics
  - job_name: 'infra-control-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Node Exporter (métriques système)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PostgreSQL metrics (si vous installez postgres_exporter)
  # - job_name: 'postgresql'
  #   static_configs:
  #     - targets: ['host.docker.internal:9187']

  # Redis metrics (si vous installez redis_exporter)  
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['host.docker.internal:9121']